import { NextResponse } from "next/server"

const subscriptionPlans = [
  {
    id: "basic_monthly",
    name: "Basic Monthly",
    description: "Access to our entire ebook library",
    price: 9.99,
    originalPrice: 12.99,
    currency: "USD",
    interval: "month",
    intervalCount: 1,
    features: [
      "Unlimited ebook access",
      "Download up to 10 books per month",
      "Read on any device",
      "Basic customer support",
      "No ads",
    ],
    limitations: ["10 downloads per month", "Standard quality"],
    popular: false,
    trialDays: 7,
    discount: 23,
  },
  {
    id: "premium_monthly",
    name: "Premium Monthly",
    description: "Everything in Basic plus premium features",
    price: 19.99,
    originalPrice: 24.99,
    currency: "USD",
    interval: "month",
    intervalCount: 1,
    features: [
      "Unlimited ebook access",
      "Unlimited downloads",
      "Read on any device",
      "Priority customer support",
      "No ads",
      "Exclusive early access",
      "Premium audiobooks included",
      "Offline reading",
    ],
    limitations: [],
    popular: true,
    trialDays: 14,
    discount: 20,
  },
  {
    id: "basic_yearly",
    name: "Basic Yearly",
    description: "Best value for regular readers",
    price: 99.99,
    originalPrice: 155.88,
    currency: "USD",
    interval: "year",
    intervalCount: 1,
    features: [
      "Unlimited ebook access",
      "Download up to 15 books per month",
      "Read on any device",
      "Priority customer support",
      "No ads",
      "2 months free",
    ],
    limitations: ["15 downloads per month", "Standard quality"],
    popular: false,
    trialDays: 30,
    discount: 36,
    savings: "Save $55.89 vs monthly",
  },
  {
    id: "premium_yearly",
    name: "Premium Yearly",
    description: "Ultimate reading experience",
    price: 199.99,
    originalPrice: 299.88,
    currency: "USD",
    interval: "year",
    intervalCount: 1,
    features: [
      "Unlimited ebook access",
      "Unlimited downloads",
      "Read on any device",
      "24/7 premium support",
      "No ads",
      "Exclusive early access",
      "Premium audiobooks included",
      "Offline reading",
      "Family sharing (up to 5 members)",
      "Advanced reading analytics",
    ],
    limitations: [],
    popular: true,
    trialDays: 30,
    discount: 33,
    savings: "Save $99.89 vs monthly",
  },
]

export async function GET() {
  return NextResponse.json({ plans: subscriptionPlans })
}
